version: '3.4'
services:
  jupyter:
    image: "${BASE_IMAGE_NAME}-dev"
    build:
      context: .
      target: dev_image
    ports:
      - '7777:7777'
    volumes:
      - .:/home/jovyan/lemma
    environment:
      TZ: Pacific/Auckland
